### PR TITLE
Add rated-voltage-ac to Capacitor

### PR DESCRIPTION
**Pull request by PhilippeFerreiraDeSousa**

### CODE REVIEW

**Comment by bpellenard** [comment]
@PhilippeFerreiraDeSousa Do you have a test where you could show how it is used?

**Comment by bpellenard** [comment]
@RajeshJITX I would suggest to add the ticket number to the commit message: 'JITX-272: Add rated-voltage-ac to Capacitor', such that we can find a commit by the ticket number in the git history

**Comment by RajeshJITX** [comment]
> @PhilippeFerreiraDeSousa Do you have a unit test where you could show how it is used?

**Comment by RajeshJITX** [comment]
Sorry Accidently closed the PR. Was trying to reply to a comment

**Comment by RajeshJITX** [comment]
@bpellenard, it is not necessary to add to every commit. When you see the attached screenshot, you will see that when the branch gets merged, you can see the entire history of the branch and all associated commits.

Screen Shot 2021-04-23 at 7 47 36 AM

**Comment by PhilippeFerreiraDeSousa** [comment]
> @RajeshJITX I would suggest to add the ticket number to the commit message: '[JITX-272](https://jitx.atlassian.net/browse/JITX-272): Add rated-voltage-ac to Capacitor', such that we can find a commit by the ticket number in the git history

Yes branch names are in the merge commit messages. But also the pull request search engine on github looks up branch names
image

**Comment by bpellenard** [comment]
@PhilippeFerreiraDeSousa that's pretty cool. I did not know that. I was using gitk and it was looking for only the commit message.

**Review by ariel-hi — APPROVED** [review]
For db-parts `Capacitor`, new `rated-voltage-ac` field that can optionally be provided in the query. Also added to printer. 👍

**Review by CuppoJava — APPROVED** [review]
Looks good to me.

**Pull request merged**
