### PR TITLE
removed SDI and SDO from SPI bundle, as these are duplicates of CIPO and COPI.

### PR DESCRIPTION
**Pull request by electricfungi**

### CODE REVIEW

**Comment by RajeshJITX** [comment]
These changes could break some generated as well existing code. If you want, you can create a temp branch like temp/suggested-changes and I will pick up changes from these branches

**Comment by d-haldane** [comment]
For these names, SDI maps to MISO, and SDO maps to MOSI.

**Comment by d-haldane** [comment]
Or maybe not. Here's the source: https://www.oshwa.org/a-resolution-to-redefine-spi-signal-names We need a chart to figure out what to call what.

**Comment by electricfungi** [comment]
Closing so we match with https://www.oshwa.org/a-resolution-to-redefine-spi-signal-names

**Pull request closed without merging**
