### PR TITLE
JITX-647: Added landpatterns utility functions for DShape, GeneralRoundedRectangle and GeneralChamferedRectangle

### PR DESCRIPTION
**Pull request by bpellenard**
…

### CODE REVIEW

**Review by m-hilgendorf — APPROVED** [review]
Looks great! The only things it the usage of single-character arguments but that is consistent with the rest of land-patterns.stanza.

**Review by CuppoJava — DISMISSED** [review]
This looks good to me. 

Can we make a JIRA ticket or TODO comment that asks us to revisit why there is this extra level of indirection in shape-creation? It seems `general-round-rect` and `GeneralRoundedRectangle` are identical, so I'm not sure what the extra code is for.

**Comment by bpellenard** [comment]
I removed the useless additional layer. It is useless since there is no need for normalization for `DShape`, `GeneralRoundedRectangle` and `GeneralChamferedRectangle`

**Review by CuppoJava — APPROVED** [review]
Thanks! Looks good.

**Pull request merged**
