### PR TITLE
Cherry MX model to landpattern

### PR DESCRIPTION
**Pull request by ariel-hi**

### CODE REVIEW

**Review by d-haldane — COMMENTED** [review]
I notice that it's using a KiCAD directory for the 3d-model. Is that intended?

**Comment by ariel-hi** [comment]
I can change the model to match the new export conventions and look like this:
`model3d = model3D("cherry-sw.wrl",
  Vec3D(0., 0., 0.),
  Vec3D(0.3937, 0.3937, 0.3937))
  Vec3D(0.0, 0.0, 0.0))`

If a user includes Cherry MX in their design, after they run their design, they should add `cherry-sw.wrl` to the JITX project's 3d-models folder.

**Comment by d-haldane** [comment]
Sounds like a plan. Same for the Kailh socket model?

**Comment by ariel-hi** [comment]
Done for both models. Also fixed a typo (swapped parenthesis and comma)

**Comment by d-haldane** [comment]
Why is the socket commented out? This would be a good example to show multiple models

**Comment by ariel-hi** [comment]
I don't have the original models, so I wasn't sure if the two models are different ways to represent Cherry MX or if they should be used together to support the landpattern.

**Comment by ariel-hi** [comment]
OK, I looked up these models. Looks like they work in tandem. Uncommenting kailh

**Review by d-haldane — APPROVED** [review]

**Pull request merged**
